SELECT reg.[ExamRegistrationID]
     ,reg.[ExamScheduleID]
     ,reg.[ExamineeID]
     ,reg.[TrainingCourseRegistrationID]
     ,reg.[TrainingTimeGapExceeded]
 ,trnschd.[StartDate]
 ,ctg.[ExamCategoryCode]
 ,ctg.[TrainingToExamGapMaxLimit]
 ,[ExamDate]
 FROM [dbo].[ExamRegistrationAndResult] reg inner join [dbo].[ExamSchedule] schd on reg.[ExamScheduleID]=schd.[ExamScheduleID]
 inner join [dbo].[ExamCategory] ctg on ctg.[ExamCategoryCode]=schd.[ExamCategoryCode]
 inner join [dbo].[TrainingCourseRegistrationAndResult] trnreg on reg.[TrainingCourseRegistrationID]=trnreg.[TrainingCourseRegistrationID]
 inner join [dbo].[TrainingCourseSchedule] trnschd on trnschd.[TrainingCourseScheduleID]=trnreg.[TrainingCourseScheduleID]
 order by [ExamRegistrationID] desc